name: dashboard_test
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab=2.1
  - jupyter-server-proxy=1.3.2
  - xarray=0.15.2
  - rasterio=1.0
  - panel=0.9.5
  - holoviews=1.13.2
  - hvplot=0.5.2
  - bokeh=2.0.1
  - gdal=3.0.4
  - geopandas=0.7
  - dask=2.14
  - datashader=0.10
  - jupyter-panel-proxy=0.1.0  
